image: tetraweb/php

before_script:
    - apt-get update
    - npm install
    - npm run build
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

stage_deploy:
  artifacts:
    paths:
      - remote/
  only:
    - deploy
  script:
    - ssh-add <(echo "$STAGING_PRIVATE_KEY")
    - ssh -p22 root@ns3056388.ip-193-70-6.eu "mkdir /var/www/html/_tmp_remote"
    - scp -P22 -r build/* root@ns3056388.ip-193-70-6.eu_host:/var/www/html/_tmp_remote
    - ssh -p22 root@ns3056388.ip-193-70-6.eu "mv /var/www/html/remote /var/www/html/remote_old && mv /var/www/html/_tmp_remote /var/www/html/remote"
    - ssh -p22 root@ns3056388.ip-193-70-6.eu "rm -rf /var/www/html/remote_old"
